POST http://127.0.0.1:3000/api/products
Content-Type: application/json


{"type": "test", "weight": 100} 



###
GET http://127.0.0.1:3000/api/products


###
GET http://127.0.0.1:3000/api/products/686937efc107a3c227c63444



###
PUT http://127.0.0.1:3000/api/products/686937efc107a3c227c63444
Content-Type: application/json


{"price": "1200"} 